name: Build Tiny OpenWrt 18.06.9 (4MB)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git unzip libssl-dev wget python3 zlib1g-dev file

      - name: Download Image Builder 18.06.9 Tiny
        run: |
          wget https://archive.openwrt.org/releases/18.06.9/targets/ar71xx/tiny/openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64.tar.xz
          cd openwrt-imagebuilder-18.06.9-ar71xx-tiny.Linux-x86_64
          echo "BUILD_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Build Tiny Image with QoS & WISP
        run: |
          cd ${{ env.BUILD_DIR }}
          make image \
            PROFILE="tl-wr740n-v6" \
            PACKAGES="wpad-mini tc kmod-sched-core ip-full -luci -uhttpd -odhcp6c -odhcpd-ipv6only -kmod-ipv6 -ip6tables -ppp -ppp-mod-pppoe -kmod-pppoe -kmod-ppp"

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-18.06-tiny-740n-v6
          # قمنا بتحديد squashfs فقط لتجنب سحب ملف initramfs الضخم
          path: ${{ env.BUILD_DIR }}/bin/targets/ar71xx/tiny/*squashfs*.bin
